/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas.Creditos;

import Vistas.Cuotas.CuotasRestantes;
import Controladores.Creditos.ControladorCH;
import Controladores.Creditos.ControladorCL;
import Modelos.Datos.Cliente;
import Vistas.Cuotas.AbonarCuota;
import Vistas.Cuotas.CuotasAbonadas;
import Vistas.VistaBanco;

/**
 *
 * @author USER
 */
public class GestionarCreditos extends javax.swing.JFrame {

    private Cliente cliente;
    
    //Instancando los controladores
    public static ControladorCH CH = new ControladorCH(); //CH se usa como abreviacion de ControladorCH
    public static ControladorCL CL = new ControladorCL(); //Cl se usa como abreviacion de ControladorCL
    
    /**
     * Creates new form GestionarCreditos
     */
    public GestionarCreditos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Constructor para transferir la informacion del cliente
     * @param cliente 
     */
    public GestionarCreditos(Cliente cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.cliente = cliente;
        
        //Determinando la usabilidad de los botones
        if( !cliente.hasCreditoActivo() ){
            btnConsultarCuotasRestantes.setEnabled(false);
            btnAbonarCuota.setEnabled(false);
            btnConsultarCuotasAbonadas.setEnabled(false);
        }else{
            btnCredito.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAbonarCuota = new javax.swing.JButton();
        btnCredito = new javax.swing.JButton();
        btnConsultarCuotasRestantes = new javax.swing.JButton();
        btnConsultarCuotasAbonadas = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ELIGE UNA OPCION", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        btnAbonarCuota.setText("ABONAR CUOTA");
        btnAbonarCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarCuotaActionPerformed(evt);
            }
        });

        btnCredito.setText("ADQUIRIR CREDITO");
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });

        btnConsultarCuotasRestantes.setText("CONSULTAR CUOTAS RESTANTES");
        btnConsultarCuotasRestantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCuotasRestantesActionPerformed(evt);
            }
        });

        btnConsultarCuotasAbonadas.setText("CONSULTAR CUOTAS ABONADAS");
        btnConsultarCuotasAbonadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCuotasAbonadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbonarCuota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarCuotasRestantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarCuotasAbonadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(86, 86, 86))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnCredito)
                .addGap(46, 46, 46)
                .addComponent(btnConsultarCuotasAbonadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnConsultarCuotasRestantes)
                .addGap(46, 46, 46)
                .addComponent(btnAbonarCuota)
                .addGap(66, 66, 66))
        );

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnVolver)
                .addGap(35, 35, 35)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*** EVENTOS DE BOTONES ***/
    
    /**
     * Metodo para ir a la ventana donde aparecen los dos creditos
     * @param evt 
     */
    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed
        Creditos ventanaCreditos = new Creditos(this.cliente);
        ventanaCreditos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreditoActionPerformed

    /**
     * Metodo para volver a la ventana principal
     * @param evt 
     */
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        VistaBanco banco = new VistaBanco();
        banco.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * Metodo para ir a la ventana de consultar las cuotas restantes
     * @param evt 
     */
    private void btnConsultarCuotasRestantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCuotasRestantesActionPerformed
        CuotasRestantes cuotas = new CuotasRestantes(this.cliente);
        cuotas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarCuotasRestantesActionPerformed

    /**
     * Metodo para ir a la ventana de abonar cuotas
     * @param evt 
     */
    private void btnAbonarCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarCuotaActionPerformed
        AbonarCuota abonarCuota = new AbonarCuota(this.cliente);
        abonarCuota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAbonarCuotaActionPerformed

    /**
     * Metodo para ir a la ventana de consultar las cuotas abonadas
     * @param evt 
     */
    private void btnConsultarCuotasAbonadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCuotasAbonadasActionPerformed
        CuotasAbonadas abonadas = new CuotasAbonadas(this.cliente);
        abonadas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarCuotasAbonadasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarCreditos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarCreditos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbonarCuota;
    private javax.swing.JButton btnConsultarCuotasAbonadas;
    private javax.swing.JButton btnConsultarCuotasRestantes;
    private javax.swing.JButton btnCredito;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
